#!/bin/sh /etc/rc.common
# Copyright (C) 2007 OpenWrt.org

START=99
USE_PROCD=1

list_servers() {
	SERVER_PARAMS=" -SER[Shost:"
	config_get host "$1" 'host'
	config_get port "$1" 'port'
	config_get atoken "$1" 'atoken'
	SERVER_PARAMS="${SERVER_PARAMS}""${host}"",Sport:""${port}"
	[ ! $atoken ] && SERVER_PARAMS=${SERVER_PARAMS}"]" || SERVER_PARAMS=${SERVER_PARAMS}",Atoken:${atoken}]"
	eval ${1}_PARAMS=\$SERVER_PARAMS
}

list_tunnels() {
	config_get_bool enabled "$1" 'enabled'
	config_get type "$1" 'type'
	config_get lhost "$1" 'lhost'
	config_get server "$1" 'server'
	config_get lport "$1" 'lport'
	config_get custom_domain "$1" 'custom_domain'
	config_get rport "$1" 'rport'
	config_get dname "$1" 'dname'
	config_get hostheader "$1" 'hostheader'
	[ -z "$lhost" ] && lhost="127.0.0.1"
	if [ "$enabled" = 1 ]; then
		eval TUNNEL_PARAMS=\$${server}_TUNNEL_PARAMS
		TUNNEL_PARAMS=$TUNNEL_PARAMS" -AddTun[Type:${type},Lhost:${lhost},Lport:${lport}"
		[ -n "$hostheader" ] && TUNNEL_PARAMS=${TUNNEL_PARAMS}",Hostheader:${hostheader}"
		[ "z"$custom_domain = "z1" ] && DTYPE="Hostname" || DTYPE="Sdname"
		[ ${type} = "tcp" ] &&
			TUNNEL_PARAMS=${TUNNEL_PARAMS}",Rport:${rport}]" ||
			TUNNEL_PARAMS=${TUNNEL_PARAMS}",${DTYPE}:${dname}]"
		echo $server" : ngrokc"$TUNNEL_PARAMS
		config_foreach list_servers 'servers'
		eval ${server}_TUNNEL_PARAMS=\$TUNNEL_PARAMS
	fi
}

run_ngrokc() {
	procd_open_instance
    procd_set_param respawn
    procd_set_param command /usr/bin/ngrokc
	eval "procd_append_param command \$${1}_PARAMS"
	eval "procd_append_param command \$${1}_TUNNEL_PARAMS"
    procd_set_param file /etc/config/v2ray
    procd_close_instance
}

start_service() {
	config_load 'ngrokc'
	config_foreach list_tunnels 'tunnel'
	config_foreach run_ngrokc 'servers'			
}

service_triggers()
{
    procd_add_reload_trigger "/etc/config/ngrokc"
}